# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marcador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['-date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'BusNo', 'verbose_name_plural': 'BusNo'},
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.AddField(
            model_name='route',
            name='BusNo',
            field=models.ManyToManyField(blank=True, to='marcador.Tag'),
        ),
        migrations.AddField(
            model_name='route',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Routes', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
