# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcador', '0002_auto_20151224_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='description',
        ),
        migrations.AddField(
            model_name='route',
            name='Longitude',
            field=models.CommaSeparatedIntegerField(default=1, max_length=512, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Like my service?'),
        ),
        migrations.AlterField(
            model_name='route',
            name='url',
            field=models.URLField(max_length=255, verbose_name='Do you want to connect with google maps?'),
        ),
    ]
